const PART_TEMPLATES = {
  BODY: ['MATERIAL', 'TYPE', 'SIZE', 'CLASS'],
  'CONNECTOR (BONNET / COVER / SIDE PIECE)': ['MATERIAL', 'TYPE', 'SIZE', 'CLASS'],
  'CLOSURE MEMBER (WEDGE / GATE / DISC / BALL)': ['MATERIAL', 'TYPE', 'SIZE', 'CLASS'],
  SEATRING: ['MATERIAL', 'OUTER DIAMETER (OD)', 'INNER DIAMETER (ID)', 'THICKNESS'],
  'STEM / SPINDLE / BACK SEAT / GLAND BUSH': ['MATERIAL', 'DIAMETER', 'LENGTH'],
  'GLAND PACKING': ['MATERIAL', 'OUTER DIAMETER (OD)', 'INNER DIAMETER (ID)', 'THICKNESS'],
  'GLAND FLANGE': ['MATERIAL', 'TYPE', 'SIZE', 'CLASS', 'THICKNESS'],
  GASKET: ['MATERIAL', 'SIZE', 'CLASS', 'OUTER DIAMETER (OD)', 'INNER DIAMETER (ID)', 'THICKNESS'],
  'STUD WITH 2 NUTS': ['MATERIAL', 'DIAMETER', 'LENGTH'],
  'STUD WITH 1 NUT': ['MATERIAL', 'DIAMETER', 'LENGTH'],
  'EYE BOLT & NUT': ['MATERIAL', 'DIAMETER', 'LENGTH'],
  'CROSS PIN WITH NUT': ['MATERIAL', 'DIAMETER', 'LENGTH'],
  'YOKE SLEEVE': ['MATERIAL', 'TYPE', 'SIZE', 'CLASS'],
  'YOKE NUT': ['MATERIAL', 'TYPE', 'SIZE', 'CLASS'],
  'HAND WHEEL': ['MATERIAL', 'DIAMETER'],
  'HAND WHEEL NUT': ['MATERIAL', 'DIAMETER'],
  'GEAR BOX': ['MATERIAL', 'TYPE', 'SIZE / MODEL NUMBER', 'BASE PLATE SIZE'],
};

module.exports = {
  PART_TEMPLATES,
};
